import { registerRootComponent } from 'expo';

import App from './App';
// Side effect: registers the Android home-screen widget task handler. Safe in
// Expo Go - the widget library falls back to a native no-op module there.
import './widget/weatherWidgetTask';
// Side effect: registers the multi-city widget's configuration screen, which
// the native WidgetConfigurationActivity launches when a user places that
// widget. Requires a real build (the activity is generated by the config
// plugin); the registration itself is harmless in Expo Go.
import './widget/widgetConfigScreen';

// registerRootComponent calls AppRegistry.registerComponent('main', () => App);
// It also ensures that whether you load the app in Expo Go or in a native build,
// the environment is set up appropriately
registerRootComponent(App);
