import { registerWidgetConfigurationScreen } from 'react-native-android-widget';
import { WidgetCityConfigScreen } from '../components/WidgetCityConfigScreen';

// Guard against duplicate registration during Fast Refresh.
const globalScope = globalThis as typeof globalThis & { __muWidgetConfigDefined?: boolean };

/**
 * Registers the multi-city widget's configuration screen.
 *
 * The library calls `AppRegistry.registerComponent('RNWidgetConfigurationScreen')`
 * and the native `WidgetConfigurationActivity` (generated by the config plugin
 * because app.json declares `widgetFeatures`) launches that component with the
 * widget's `widgetInfo` as initial props.
 *
 * IMPORTANT: this only works in a real build, not Expo Go - the configuration
 * activity is generated by the native config plugin, and the AndroidWidget
 * TurboModule falls back to a no-op module in Expo Go. The registration itself
 * is harmless there.
 */
if (!globalScope.__muWidgetConfigDefined) {
  globalScope.__muWidgetConfigDefined = true;
  registerWidgetConfigurationScreen(WidgetCityConfigScreen);
}